print("24 December 2019, Christmas Eve")
print()
print("Dear Self,")
print("I hope to learn new skills in a week")
print("I hope to develop better mindset for 2020")
print("I hope to have a better portfolio")
print("I hope to have an expanded and more trustworthy social circle")
print()
print("Yours only,")
print("Eby Don")
